from typing import List, Optional, Protocol, runtime_checkable

@runtime_checkable
class Repository(Protocol):
    """Marker interface for all repositories."""
    pass

class RawSourceRepository(Protocol):
    async def save_source(self, source_data: dict) -> str: ...
    async def get_sources(self, filters: Optional[dict] = None) -> List[dict]: ...

class SignalRepository(Protocol):
    async def save_signal(self, signal_data: dict) -> str: ...
    async def get_signals(self, entity_id: str) -> List[dict]: ...

class DossierRepository(Protocol):
    async def save_dossier(self, dossier_data: dict) -> str: ...
    async def get_dossier(self, dossier_id: str) -> Optional[dict]: ...

class TimelineRepository(Protocol):
    async def save_timeline_event(self, event_data: dict) -> str: ...
    async def get_timeline(self, entity_id: str) -> List[dict]: ...
